BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE interventions CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE moodlogs CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE psychologists CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE screen_time CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE sessions CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    registration_date DATE NOT NULL,
    department VARCHAR2(50),
    position VARCHAR2(50),
    birth_date DATE,
    gender CHAR(1),
    country VARCHAR2(50),
    password VARCHAR2(50),
    username VARCHAR2(50) UNIQUE
);

CREATE TABLE sessions (
    session_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    notes CLOB,
    session_date DATE,
    session_type VARCHAR2(100),
    duration_minutes NUMBER,
    rating NUMBER,
    feedback CLOB,
    followup_required CHAR(1)
);

CREATE TABLE interventions (
    inter_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    inter_type VARCHAR2(50),
    inter_recommendation NCLOB,
    inter_created_date DATE,
    inter_implemented CHAR(1),
    inter_followup_date DATE,
    inter_res_person VARCHAR2(100),
    inter_priority_level VARCHAR2(100),
    inter_status VARCHAR2(100),
    user_id NUMBER NOT NULL,
    CONSTRAINT interventions_user_fk FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE moodlogs (
    mood_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    mood_score NUMBER,
    mood_date DATE,
    mood_stress_level NUMBER,
    mood_sleep_hours NUMBER(5,2),
    mood_energy_level NUMBER,
    mood_notes CLOB,
    mood_type VARCHAR2(50),
    workday_type VARCHAR2(50),
    user_id NUMBER NOT NULL,
    CONSTRAINT moodlogs_user_fk FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE psychologists (
    psy_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    email VARCHAR2(100) UNIQUE,
    phone_number VARCHAR2(20),
    specialization VARCHAR2(50),
    years_experience NUMBER,
    available_days VARCHAR2(100),
    available_hours VARCHAR2(100),
    assigned_user_count NUMBER,
    license_number VARCHAR2(100)
);

CREATE TABLE screen_time (
    screen_record_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    hours_worked NUMBER(5,2),
    breaks_taken NUMBER,
    focus_minutes NUMBER,
    distraction_minutes NUMBER,
    overtime_hours NUMBER(5,2),
    device_type VARCHAR2(50),
    session_start_time DATE,
    session_end_time DATE,
    user_id NUMBER NOT NULL,
    CONSTRAINT screentime_user_fk FOREIGN KEY (user_id) REFERENCES users(user_id)
);
INSERT INTO users (name, email, registration_date, department, position, password, username)
VALUES ('Admin Tester', 'admin@mindwork.com', SYSDATE, 'TI', 'Dev', '123456', 'admin');